#!/bin/bash

echo "Installing..."

# -------------------------
# Directories
# -------------------------
src="./"
dest="$HOME/.local/share/themes"

install() {
    local src=$1
    local dest=$2
    echo "Installing $src..."
    cp -r "$src/Lab-Aqua-Dark" "$dest"
	cp -r "$src/Lab-Aqua-Dots" "$dest"
	cp -r "$src/Lab-Aqua-Gradient" "$dest"
	cp -r "$src/Lab-Aqua-Pills" "$dest"
	cp -r "$src/Lab-Aqua7" "$dest"
	cp -r "$src/Lab-Aquadrop" "$dest"
	cp -r "$src/Lab-Arc-Dark" "$dest"
	cp -r "$src/Lab-Arc-Light" "$dest"
	cp -r "$src/Lab-Blueberry" "$dest"
	cp -r "$src/Lab-Bluelook" "$dest"
	cp -r "$src/Lab-Bluish" "$dest"
	cp -r "$src/Lab-Breeze-Dark" "$dest"	
	cp -r "$src/Lab-Breeze-Light" "$dest"
	cp -r "$src/Lab-Brisa" "$dest"
	cp -r "$src/Lab-Brisa-Translucid" "$dest"
	cp -r "$src/Lab-Catppuccin" "$dest"
	cp -r "$src/Lab-Catppuccin-Frappe" "$dest"
	cp -r "$src/Lab-Catppuccin-Latte" "$dest"
	cp -r "$src/Lab-Catppuccin-Macchiato" "$dest"
	cp -r "$src/Lab-Chimera" "$dest"
	cp -r "$src/Lab-Chimera-Dark" "$dest"
	cp -r "$src/Lab-Chimera-Light" "$dest"
	cp -r "$src/Lab-Chimera-Night" "$dest"
	cp -r "$src/Lab-Clearlook-Alfa" "$dest"
	cp -r "$src/Lab-Crocus" "$dest"
	cp -r "$src/Lab-DimGray" "$dest"
	cp -r "$src/Lab-Dracula" "$dest"
	cp -r "$src/Lab-Drak" "$dest"
	cp -r "$src/Lab-Drak-thin" "$dest"
	cp -r "$src/Lab-Edna" "$dest"
	cp -r "$src/Lab-Evergreen" "$dest"
	cp -r "$src/Lab-Latte" "$dest"
	cp -r "$src/Lab-Lila" "$dest"
	cp -r "$src/Lab-Liquid-Dark" "$dest"
	cp -r "$src/Lab-Liquid-Glass" "$dest"
	cp -r "$src/Lab-Mac-Dark" "$dest"
	cp -r "$src/Lab-Mac-Light" "$dest"
	cp -r "$src/Lab-MacOS-Leopard" "$dest"
	cp -r "$src/Lab-MacOS-Lion" "$dest"
	cp -r "$src/Lab-Nord" "$dest"
	cp -r "$src/Lab-Nord-Dark" "$dest"
	cp -r "$src/Lab-Nordic-Blue" "$dest"
	cp -r "$src/Lab-Orchis" "$dest"
	cp -r "$src/Lab-Orchis-Dark" "$dest"
	cp -r "$src/Lab-Oxygen" "$dest"
	cp -r "$src/Lab-Oxygen-Glass" "$dest"
	cp -r "$src/Lab-Purple" "$dest"
	cp -r "$src/Lab-Sky" "$dest"
	cp -r "$src/Lab-Star" "$dest"
	cp -r "$src/Lab-TokyoNight" "$dest"
	cp -r "$src/Lab-Vintage" "$dest"
	cp -r "$src/Lab-w10" "$dest"
	cp -r "$src/Lab-W11" "$dest"
	cp -r "$src/Lab-W11-Silver" "$dest"
	cp -r "$src/Lab-W7" "$dest"
	cp -r "$src/Lab-WhiteSur-small" "$dest"
	cp -r "$src/Lab-xp-blue" "$dest"
	cp -r "$src/Lab-xp-metal" "$dest"
	cp -r "$src/Lab-xp-noir" "$dest"
	cp -r "$src/Lab-xp-royale" "$dest"
}

install "$src" "$dest"

echo ""
echo "Installation complete!"
echo ""

